receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']

processors:
  batch:


exporters:
  # OTLP
  otlp:
    endpoint: otelcol:4317
  # Data sources: traces
  logging:
    loglevel: debug  
  # Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging, prometheus]