version: '3.1'
services:
  db:
    image: postgres:16.1
    volumes:
      - "pgdata:/var/lib/postgresql/data/pgdata"
    restart: always
    environment:
      POSTGRES_PASSWORD: posgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  pgdata:
    driver: local
