apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    {{- include "orm-usm-webapi.labels" . | nindent 4 }}
  name: {{ include "orm-usm-webapi.fullname" . }}
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "orm-usm-webapi.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "orm-usm-webapi.labels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          name: {{ include "orm-usm-webapi.name" . }}
          env:
            - name: spring_datasource_url
              value: {{ .Values.application.datasource | quote }}
            - name: app_kafka_producer_bootstrap-servers
              value: {{ .Values.application.kafka.brokers | quote }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
