# Default values for orm-usm-bd-init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: db-migration
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.2.0"

nameOverride: ""
fullnameOverride: ""

db:
  host: 192.168.1.15
  port: 5432
  pguser: postgres
  pgpass: posgres
  name: orm_usm
  dbauser: tec_orm_usm_dba
  dbapass: tec_orm_usm_dba
  appuser: tec_orm_usm_app
  apppass: tec_orm_usm_app